Optimize compose & DoMany
fragcolor-xyz/shards pull request #1023
Opened 2024-07-25 13:16 UTC by guusw

2024-07-26 01:56 UTC, sinkingsugar commented
Still very surprised that boost flat_map was so much slower

2024-07-26 01:58 UTC, sinkingsugar commented
Btw the best optimization would be to recycle this https://github.com/fragcolor-xyz/shards/blob/1fa4e158c499f422ede2d46ec92720a16d936a4d/shards/core/runtime.cpp#L850 - should be easy to keep it in context

2024-07-26 07:19 UTC, guusw commented
> Btw the best optimization would be to recycle this
> 
> https://github.com/fragcolor-xyz/shards/blob/1fa4e158c499f422ede2d46ec92720a16d936a4d/shards/core/runtime.cpp#L850
> - should be easy to keep it in context

Didn't even see that one, can fix that yes

2024-07-26 07:36 UTC, guusw commented
Oh that's devel, nvm

2024-07-30 06:05 UTC, sinkingsugar requested changes
Minor stuff

2024-07-30 06:05 UTC, sinkingsugar commented on shards/core/serialization.hpp
> +    // Uncomment for more detailed breakdown
Maybe `#if 0` it instead?

2024-07-30 06:05 UTC, sinkingsugar commented on shards/core/wire_doppelganger_pool.hpp
> +    // pmr::SharedTempAllocator tempAlloc;
Delete?

2024-08-01 06:39 UTC, sinkingsugar approved these changes

2024-08-01 08:57 UTC, merged