Rust var as i32
fragcolor-xyz/shards pull request #276
Opened 2022-06-13 12:14 UTC by inabe-a

Adding From<T>, TryFrom<T> impl in Rust for Var for vector types with up to 4 elements.

https://github.com/fragcolor-xyz/shards/issues/263

**Test plan**
Will need additional testing.

2022-06-13 12:21 UTC, sinkingsugar commented
`half`/`f16` is interesting but not being "standard" makes it less useful.
Is the rust community mostly converging using `half` crate though? In that case maybe why not.

2022-06-15 08:44 UTC, guusw requested changes

2022-06-15 13:33 UTC, inabe-a commented
Tested locally, but I haven't enabled `cargo test` here. We probably want to push that separately.
https://discord.com/channels/969754837220737054/969766235967459419/986549166673129512

2022-06-15 13:36 UTC, inabe-a commented on rust/src/types.rs
> +  test_to_from_vec4!(half::f16, half::f16::EPSILON, "[half::f16,4] conversion failed");
Shards is so sharp, it cuts the epsilon in half 🎉

2022-06-17 06:16 UTC, sinkingsugar commented
Considering that I'm now propagating errors et al in #279 we should reconsider the overflow handling. We might wanna error on i64 overflow.

2022-06-17 15:45 UTC, merged