Render graph & post effect passes
fragcolor-xyz/shards pull request #434
Opened 2022-10-18 09:00 UTC by guusw

Changes to implement #172 
No shard changes to keep a smaller PR

2022-11-12 11:04 UTC, sinkingsugar requested changes
Half way, couple of questions/points, looking good though!

2022-11-14 12:18 UTC, guusw commented on .github/workflows/build-linux.yml
> +    runs-on: ubuntu-22.04
I just needed to make sure gcc-11 is available, which I know for sure on that image.
Latest might be okay though, I'll try that.

2022-11-15 13:40 UTC, guusw commented on src/gfx/CMakeLists.txt
> +  spdlog stb xxHash Boost::algorithm Boost::filesystem Boost::uuid
I didn't want to hash the entire structures using them (Feature/RenderStep) so I assigned them ids and treat them as immutable.
I don't have too many options without adding new libraries, or rust interop to crypto libraries.
I can use xxHash with time input, but I guess I might as well just use an atomic counter (doesn't need to be cryptographically secure, just unique)

2022-11-15 17:53 UTC, guusw commented on .github/workflows/build-linux.yml
> +    runs-on: ubuntu-22.04
For some reason 'latest' evaluates to `ubuntu-20.04` so that's why I put it explicit

2022-11-16 13:30 UTC, guusw commented on src/gfx/enums.cpp
> +  case StorageType::Float32:
Add coverage for these formats.

2022-11-21 13:01 UTC, guusw commented on src/gfx/CMakeLists.txt
> +  spdlog stb xxHash Boost::algorithm Boost::filesystem Boost::uuid
Replace with simple counter to simplify & avoid confusion.

2022-11-22 09:01 UTC, sinkingsugar approved these changes
Ok but We need to document well the renderer very soon.
Not just cos it's getting complex but also because it's amazing to showcase.

2022-11-22 10:06 UTC, Kryptos-FR approved these changes
LGTM.

Small remarks but nothing critical.

2022-11-22 10:06 UTC, Kryptos-FR commented on src/gfx/tests/test_general.cpp
> +  for (size_t i = 0; i < 16; i++) {
Why increase here? Might be good to add a comment with the rationale.

2022-11-22 10:31 UTC, guusw commented on .github/workflows/build-linux.yml
> +  CXX: g++-11
I was using a specific c++17 feature I believe, which only really started working starting from gcc-11

2022-11-22 10:33 UTC, guusw commented on src/gfx/unique_id.hpp
> +    return counter.fetch_add(1, std::memory_order_relaxed);
Yeah can add a comment

2022-11-22 11:01 UTC, Kryptos-FR commented on .github/workflows/build-linux.yml
> +    runs-on: ubuntu-22.04
That's weird that `-latest` wasn't already on `22.04` given it was GA 7 months ago, but apparently that will only be the case in December: https://github.com/actions/runner-images/issues/6399

2022-11-23 09:33 UTC, guusw commented on .github/workflows/build-linux.yml
> +  CXX: g++-11
I believe 10 was latest on ubuntu 20

2022-11-24 13:05 UTC, merged