3rd Draft of the "Shards Flow" Chapter
fragcolor-xyz/shards pull request #542
Opened 2023-02-01 03:30 UTC by ChelseaChX

- Added figures
- Fixed some formatting
- Added the segment on Stepmany, Branch and TryMany

2023-02-02 03:07 UTC, sinkingsugar commented
how to review it properly? Is there a temporary page?

2023-02-02 03:22 UTC, ChelseaChX commented
> how to review it properly? Is there a temporary page?

Currently we're using mkdocs to preview with a static site. I can put it on GitBook so that it is easier for you and Guus to review. I'll link the page here once I've moved the content over.

2023-02-02 03:36 UTC, sinkingsugar commented
> > how to review it properly? Is there a temporary page?
> 
> Currently we're using mkdocs to preview with a static site. I can put it on GitBook so that it is easier for you and Guus to review. I'll link the page here once I've moved the content over.

I definitely cannot go to the extent do setup mkdocs, so something ready to consume is needed

2023-02-02 04:17 UTC, ChelseaChX commented
@sinkingsugar @guusw 

Here is the gitbook link for review. Thank you!

https://app.gitbook.com/o/3P6QfbtIO6GdyTCAishv/s/kU8RKpFJAomTkF4Ipcxy/the-flow

2023-02-02 08:29 UTC, guusw requested changes
Still reading over Spawn/Resume

2023-02-02 08:29 UTC, guusw commented on docs/docs/learn/shards/the-flow.md
> +- `Spawn` schedules clones of the Wire.
"Spawn schedules a clone of the wire" sounds better I think

2023-02-02 08:29 UTC, guusw commented on docs/docs/learn/shards/the-flow.md
> +    (Branch [wire-x, wire-y, wire-z]) ;; (1)
Remove `,`

2023-02-03 10:03 UTC, ChelseaChX commented
@guusw I've removed the mentions on Dispatch and integrated the comments given. I've left out mentions of Passthrough for now, will be adding that to the following chapter.

2023-02-07 09:19 UTC, merged