CRDT
fragcolor-xyz/shards pull request #657
Opened 2023-04-07 08:45 UTC by sinkingsugar

2023-04-27 08:53 UTC, sinkingsugar commented on src/core/runtime.cpp
> +void* operator new(std::size_t count) {
@guusw can you check why stacktraces are not avail?

2023-04-27 20:11 UTC, guusw requested changes
For me it breaks at startup (during static initializers), can you maybe add a check so tracking is only enabled after main/shards init is called

<img width="1118" alt="tracy" src="https://user-images.githubusercontent.com/16842774/234979480-8c45b4ac-8038-4391-9b9e-18ee0d687395.PNG">

2023-04-28 01:42 UTC, sinkingsugar commented on src/core/runtime.cpp
> +    void* ptr = std::aligned_alloc(align_value, aligned_count);
Github copilot had a better answer

2023-04-28 08:40 UTC, guusw commented
Will push windows fixes to this branch

2023-04-30 23:57 UTC, sinkingsugar commented
Merged with #664

2023-04-30 23:57 UTC, closed without merging