First draft of AI Query Cards
fragcolor-xyz/shards pull request #871
Opened 2023-11-20 09:46 UTC by ShahFragcolor

**Description**

**Test plan**

2023-11-20 09:51 UTC, sinkingsugar requested changes

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/and_query.shs
> +      ;; DoSomething
Better to use `Pass` cos it will fail to parse without a shard here! so more like
```
Pass ; Do Something
```

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/and_query.shs
> +    variable
`Get(variable)` etc

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/and_query.shs
> +    When(Predicate: {Is(condition1) | And | variable2 | Is(condition2)} Action: {
`Get(variable2)`

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/appendTo_query.shs
> +    element | AppendTo(Collection: sequence)
Get

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/const_query.shs
> +   Const(value)
`value`

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/count_query2.shs
> +   Count(tableToCount)
`table-to-count` prefer kebab cases

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/count_query3.shs
> +   Count(tableToCount keyToCount)
kebab

2023-11-20 09:51 UTC, sinkingsugar commented on ai/fine-tuning-v1/is_query.shs
> +    variable1
Get

2023-11-20 09:54 UTC, sinkingsugar commented on ai/fine-tuning-v1/push_query.shs
> +  solutions: [{
let's remove solutions and explicits, and just add more examples

2023-11-30 23:47 UTC, sinkingsugar commented on ai/fine-tuning-v1/general-wires/detach_query.shs
> +    Detach will  execute a wire concurrently in the background within the same mesh as the parent wire. Only one wire of each unique wire
extra space

2023-11-30 23:48 UTC, sinkingsugar commented on ai/fine-tuning-v1/general-wires/detach_query.shs
> +    can be detached at any point in time. Subsequent detaches of the same wire, will be ignored.
Unless restart parameter is specified, also the whole one wire of each unique wire I'm not sure

2023-11-30 23:50 UTC, sinkingsugar commented
Something is wrong with this PR I see unrelated commits, can you check with @guusw ?

2024-01-03 10:01 UTC, guusw requested changes

2024-01-03 10:01 UTC, guusw commented on scripts/test-code.shs
> +@wire(main-wire{
Do we need this script here?

2025-01-19 03:37 UTC, closed without merging